version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: nqCWz8hm2RpDtPv2
      MYSQL_DATABASE: django
      MYSQL_USER: django
      MYSQL_PASSWORD: nqCWz8hm6RpDtPv2
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db