# Generated by Django 4.2.7 on 2023-11-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_home', models.IntegerField()),
                ('goals_away', models.IntegerField()),
                ('team_away', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='competitions.team')),
                ('team_home', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='competitions.team')),
            ],
        ),
    ]
