# Generated by Django 4.2.7 on 2023-11-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_alter_match_goals_away_alter_match_goals_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sport_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.sporttype'),
        ),
    ]
