# Generated by Django 4.2.7 on 2023-12-05 10:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 10, 33, 3, 327631, tzinfo=datetime.timezone.utc), verbose_name='match date'),
            preserve_default=False,
        ),
    ]
