# Generated by Django 4.2.7 on 2023-12-05 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='competitions.competition'),
        ),
    ]
