# Generated by Django 4.2.7 on 2023-12-05 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_player_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name': 'Wettbewerb', 'verbose_name_plural': 'Wettbewerbe'},
        ),
        migrations.AlterModelOptions(
            name='gendertype',
            options={'verbose_name': 'Geschlecht', 'verbose_name_plural': 'Geschlechter'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Spiel', 'verbose_name_plural': 'Spiele'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Spieler', 'verbose_name_plural': 'Spieler'},
        ),
        migrations.AlterModelOptions(
            name='sporttype',
            options={'verbose_name': 'Sportart', 'verbose_name_plural': 'Sportarten'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
